# Generated by Django 4.1.7 on 2023-04-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApi', '0003_trade_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='start_date',
            field=models.DateField(),
        ),
    ]
