# Generated by Django 4.1.7 on 2023-04-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApi', '0004_alter_trade_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='end_date',
            field=models.DateField(),
        ),
    ]
